### ISSUE TITLE
Scan n Plan Demo application not working as expected

### ISSUE THREAD

**Issue by JagadeshManivannan** [rosin-project/automatica18_scan_and_plan_demo#21]
I've been trying to see the simulation of this application for the past 4 days. The build is successful, but when I use the launch command "roslaunch snp_prbt_bringup application_bringup.launch", I don't see anything in the gazebo window.  I'm using Ros Kinetic. After this error below, I tried also to launch the godel demo. In that case, the application starts in the RViZ window with the robot, but still I don't see the object models. Do you have any documentation that I could follow? Kindly help me resolve this error.  This is the error that I receive in the terminal while launching the "roslaunch snp_prbt_bringup application_bringup.launch":

```
[ INFO] [1571748295.037626463]: Loading gazebo_ros_control plugin
[ERROR] [1571748295.038085270]: GazeboRosControlPlugin missing <legacyModeNS> while using DefaultRobotHWSim, defaults to true.
This setting assumes you have an old package with an old implementation of DefaultRobotHWSim, where the robotNamespace is disregarded and absolute paths are used instead.
If you do not want to fix this issue in an old package just set <legacyModeNS> to true.

[ INFO] [1571748295.039202110]: Starting gazebo_ros_control plugin in namespace: prbt
[ INFO] [1571748295.041640703]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[spawn_urdf-4] process has finished cleanly
log file: /home/rd/.ros/log/b5045c9a-f4c9-11e9-aa7a-080027772738/spawn_urdf-4*.log
[ERROR] [1571748295.473086407]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/prbt_joint_1
[ERROR] [1571748295.482466526]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/prbt_joint_2
[ERROR] [1571748295.487030974]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/prbt_joint_3
[ERROR] [1571748295.488728553]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/prbt_joint_4
[ERROR] [1571748295.494319459]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/prbt_joint_5
[ERROR] [1571748295.499002202]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/prbt_joint_6
[ INFO] [1571748295.563652354]: Loaded gazebo_ros_control.
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 207, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 199, in main
    resp = switch_controller(loaded, [], 2)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[WARN] [1571748302.043394, 0.000000]: Controller Spawner error while taking down controllers: unable to connect to service: [Errno 104] Connection reset by peer
Segmentation fault (core dumped)
[gazebo-2] process has died [pid 9828, exit code 139, cmd /home/rd/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver -u -e ode /home/rd/snp_demo_ws/src/automatica18_scan_and_plan_demo/snp_prbt_description/worlds/prbt_robot.world __name:=gazebo __log:=/home/rd/.ros/log/b5045c9a-f4c9-11e9-aa7a-080027772738/gazebo-2.log].
log file: /home/rd/.ros/log/b5045c9a-f4c9-11e9-aa7a-080027772738/gazebo-2*.log
[prbt/controller_spawner-5] process has died [pid 9839, exit code 1, cmd /opt/ros/kinetic/lib/controller_manager/spawner manipulator_joint_trajectory_controller manipulator_joint_state_controller __name:=controller_spawner __log:=/home/rd/.ros/log/b5045c9a-f4c9-11e9-aa7a-080027772738/prbt-controller_spawner-5.log].
log file: /home/rd/.ros/log/b5045c9a-f4c9-11e9-aa7a-080027772738/prbt-controller_spawner-5*.log
```

Thanks in advance!

Jagadesh

**Comment by scott320** [comment]
@Jagadesh    Did you fix up the problem? I have the same error with you.

**Comment by hsd-dev** [comment]
The code has not been touched in more than 2 years, so I would expect some issues. Please follow https://github.com/rosin-project/automatica18_scan_and_plan_demo/issues/22 where I am trying to port it to `melodic`.
